# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Team.create([
  {
    name:       "United States Air Force Academy",
    name_short: "Air Force",
    abbrev:     "AFA",
    nickname:   "Falcons",
    city:       "Colorado Springs",
    state:      "Colorado",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/air-force.svg"
  },
  {
    name:       "University of Akron",
    name_short: "Akron",
    abbrev:     "AKR",
    nickname:   "Zips",
    city:       "Akron",
    state:      "Ohio",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/akron.svg"
  },
  {
    name:       "University of Alabama",
    name_short: "Alabama",
    abbrev:     "ALA",
    nickname:   "Crimson Tide",
    city:       "Tuscaloosa",
    state:      "Alabama",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/alabama.svg"
  },
  {
    name:       "Appalachian State University",
    name_short: "App. State",
    abbrev:     "APP",
    nickname:   "Mountaineers",
    city:       "Boone",
    state:      "North Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/appalachian-st.svg"
  },
  {
    name:       "University of Arizona",
    name_short: "Arizona",
    abbrev:     "ARIZ",
    nickname:   "Wildcats",
    city:       "Tuscon",
    state:      "Arizona",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/arizona.svg"
  },
  {
    name:       "Arizona State University",
    name_short: "Arizona St.",
    abbrev:     "ASU",
    nickname:   "Sun Devils",
    city:       "Tempe",
    state:      "Arizona",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/arizona-st.svg"
  },
  {
    name:       "University of Arkansas",
    name_short: "Arkansas",
    abbrev:     "ARK",
    nickname:   "Razorbacks",
    city:       "Fayetteville",
    state:      "Arkansas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/arkansas.svg"
  },
  {
    name:       "Arkansas State University",
    name_short: "Arkansas St.",
    abbrev:     "ARST",
    nickname:   "Red Wolves",
    city:       "Jonesboro",
    state:      "Arkansas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/arkansas-st.svg"
  },
  {
    name:       "United States Military Academy",
    name_short: "Army",
    abbrev:     "ARMY",
    nickname:   "Black Knights",
    city:       "West Point",
    state:      "New York",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/army.svg"
  },
  {
    name:       "Auburn University",
    name_short: "Auburn",
    abbrev:     "AUB",
    nickname:   "Tigers",
    city:       "Auburn",
    state:      "Alabama",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/auburn.svg"
  },
  {
    name:       "Ball State University",
    name_short: "Ball St.",
    abbrev:     "BALL",
    nickname:   "Cardinals",
    city:       "Muncie",
    state:      "Indiana",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/ball-st.svg"
  },
  {
    name:       "Baylor University",
    name_short: "Baylor",
    abbrev:     "BAY",
    nickname:   "Bears",
    city:       "Waco",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/baylor.svg"
  },
  {
    name:       "Boise State University",
    name_short: "Boise St.",
    abbrev:     "BSU",
    nickname:   "Broncos",
    city:       "Boise",
    state:      "Idaho",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/boise-st.svg"
  },
  {
    name:       "Boston College",
    name_short: "Boston College",
    abbrev:     "BC",
    nickname:   "Eagles",
    city:       "Chestnut Hill",
    state:      "Massachusetts",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/boston-college.svg"
  },
  {
    name:       "Bowling Green State University",
    name_short: "Bowling Green",
    abbrev:     "BGSU",
    nickname:   "Falcons",
    city:       "Bowling Green",
    state:      "Ohio",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/bowling-green.svg"
  },
  {
    name:       "University at Buffalo",
    name_short: "Buffalo",
    abbrev:     "BUFF",
    nickname:   "Bulls",
    city:       "Buffalo",
    state:      "New York",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/buffalo.svg"
  },
  {
    name:       "Bringham Young University",
    name_short: "Bringham Young",
    abbrev:     "BYU",
    nickname:   "Cougars",
    city:       "Provo",
    state:      "Utah",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/byu.svg"
  },
  {
    name:       "University of California",
    name_short: "California",
    abbrev:     "CAL",
    nickname:   "Golden Bears",
    city:       "Berkley",
    state:      "California",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/california.svg"
  },
  {
    name:       "Central Michigan University",
    name_short: "Central Mich.",
    abbrev:     "CMU",
    nickname:   "Chippewas",
    city:       "Mount Pleasant",
    state:      "Michigan",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/central-mich.svg"
  },
  {
    name:       "UNC Charlotte",
    name_short: "Charlotte",
    abbrev:     "CLT",
    nickname:   "49ers",
    city:       "Charlotte",
    state:      "North Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/charlotte.svg"
  },
  {
    name:       "University of Cincinnati",
    name_short: "Cincinnati",
    abbrev:     "CIN",
    nickname:   "Bearcats",
    city:       "Cincinnati",
    state:      "Ohio",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/cincinnati.svg"
  },
  {
    name:       "Clemson University",
    name_short: "Clemson",
    abbrev:     "CLEM",
    nickname:   "Tigers",
    city:       "Clemson",
    state:      "South Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/clemson.svg"
  },
  {
    name:       "Coastal Carolina University",
    name_short: "Coastal Carolina",
    abbrev:     "CCU",
    nickname:   "Chanticleers",
    city:       "Conway",
    state:      "South Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/coastal-caro.svg"
  },
  {
    name:       "University of Colorado",
    name_short: "Colorado",
    abbrev:     "COLO",
    nickname:   "Buffaloes",
    city:       "Boulder",
    state:      "Colorado",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/colorado.svg"
  },
  {
    name:       "Colorado State University",
    name_short: "Colorado St.",
    abbrev:     "CSU",
    nickname:   "Rams",
    city:       "Fort Collins",
    state:      "Colorado",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/colorado-st.svg"
  },
  {
    name:       "Duke University",
    name_short: "Duke",
    abbrev:     "DUKE",
    nickname:   "Blue Devils",
    city:       "Durham",
    state:      "North Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/duke.svg"
  },
  {
    name:       "East Carolina University",
    name_short: "East Carolina",
    abbrev:     "ECU",
    nickname:   "Pirates",
    city:       "Greensville",
    state:      "North Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/east-carolina.svg"
  },
  {
    name:       "Eastern Michigan University",
    name_short: "Eastern Mich.",
    abbrev:     "ENU",
    nickname:   "Eagles",
    city:       "Ypsilanti",
    state:      "Michigan",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/eastern-mich.svg"
  },
  {
    name:       "Florida International University",
    name_short: "Florida Int.",
    abbrev:     "FIU",
    nickname:   "Panthers",
    city:       "Miami",
    state:      "Florida",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/fiu.svg"
  },
  {
    name:       "University of Florida",
    name_short: "Florida",
    abbrev:     "FLA",
    nickname:   "Gators",
    city:       "Gainesville",
    state:      "Florida",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/florida.svg"
  },
  {
    name:       "Florida Atlantic University",
    name_short: "Florida Atlantic",
    abbrev:     "FAU",
    nickname:   "Owls",
    city:       "Boca Raton",
    state:      "Florida",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/fla-atlantic.svg"
  },
  {
    name:       "Florida State University",
    name_short: "Florida St.",
    abbrev:     "FSU",
    nickname:   "Seminoles",
    city:       "Tallahassee",
    state:      "Florida",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/florida-st.svg"
  },
  {
    name:       "Fresno State",
    name_short: "Fresno St.",
    abbrev:     "FRES",
    nickname:   "Bulldogs",
    city:       "Fresno",
    state:      "California",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/fresno-st.svg"
  },
  {
    name:       "University of Georgia",
    name_short: "Georgia",
    abbrev:     "UGA",
    nickname:   "Bulldogs",
    city:       "Athens",
    state:      "Georgia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/georgia.svg"
  },
  {
    name:       "Georgia State University",
    name_short: "Georgia St.",
    abbrev:     "GAST",
    nickname:   "Panthers",
    city:       "Atlanta",
    state:      "Georgia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/georgia-st.svg"
  },
  {
    name:       "Georgia Tech",
    name_short: "Georgia Tech",
    abbrev:     "GT",
    nickname:   "Yellow Jackets",
    city:       "Atlanta",
    state:      "Georgia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/georgia-tech.svg"
  },
  {
    name:       "University of Hawaii, Manoa",
    name_short: "Hawaii",
    abbrev:     "HAW",
    nickname:   "Rainbow Warriors",
    city:       "Honolulu",
    state:      "Hawaii",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/hawaii.svg"
  },
  {
    name:       "University of Houston",
    name_short: "Houston",
    abbrev:     "HOU",
    nickname:   "Cougars",
    city:       "Houston",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/houston.svg"
  },
  {
    name:       "University of Illinois",
    name_short: "Illinois",
    abbrev:     "ILL",
    nickname:   "Fighting Illini",
    city:       "Champaign",
    state:      "Illinois",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/illinois.svg"
  },
  {
    name:       "University of Indiana",
    name_short: "Indiana",
    abbrev:     "IU",
    nickname:   "Hoosiers",
    city:       "Bloomington",
    state:      "Indiana",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/indiana.svg"
  },
  {
    name:       "University of Iowa",
    name_short: "Iowa",
    abbrev:     "IOWA",
    nickname:   "Hawkeyes",
    city:       "Iowa City",
    state:      "Iowa",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/iowa.svg"
  },
  {
    name:       "Iowa State University",
    name_short: "Iowa State",
    abbrev:     "ISU",
    nickname:   "Cyclones",
    city:       "Ames",
    state:      "Iowa",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/iowa-st.svg"
  },
  {
    name:       "Jacksonville State University",
    name_short: "Jacksonville St.",
    abbrev:     "",
    nickname:   "Gamecocks",
    city:       "Jacksonville",
    state:      "Alabama",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "James Madison University",
    name_short: "James Madison",
    abbrev:     "",
    nickname:   "Dukes",
    city:       "Harrisonburg",
    state:      "Virginia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Kansas",
    name_short: "Kansas",
    abbrev:     "KU",
    nickname:   "Jaykawks",
    city:       "Lawrence",
    state:      "Kansas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/kansas.svg"
  },
  {
    name:       "Kansas State University",
    name_short: "Kansas St.",
    abbrev:     "KSU",
    nickname:   "Wildcats",
    city:       "Manhattan",
    state:      "Kansas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/kansas-st.svg"
  },
  {
    name:       "Kent State University",
    name_short: "Kent St.",
    abbrev:     "KSU",
    nickname:   "Golden Flashes",
    city:       "Kent",
    state:      "Ohio",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/kent-st.svg"
  },
  {
    name:       "University of Kentucky",
    name_short: "Kentucky",
    abbrev:     "UK",
    nickname:   "Wildcats",
    city:       "Lexington",
    state:      "Kentucky",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/kentucky.svg"
  },
  {
    name:       "Liberty University",
    name_short: "Liberty",
    abbrev:     "LIB",
    nickname:   "Flames",
    city:       "Lynchburg",
    state:      "Virginia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/liberty.svg"
  },
  {
    name:       "University of Louisiana at Lafayette",
    name_short: "La. Lafayette",
    abbrev:     "UL",
    nickname:   "Ragin' Cajuns",
    city:       "Lafayette",
    state:      "Louisiana",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/la-lafayette.svg"
  },
  {
    name:       "University of Louisiana Monroe",
    name_short: "La. Monroe",
    abbrev:     "ULM",
    nickname:   "Warhawks",
    city:       "Monroe",
    state:      "Lou",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/la-monroe.svg"
  },
  {
    name:       "Louisiana Tech University",
    name_short: "Louisiana Tech",
    abbrev:     "LT",
    nickname:   "Bulldogs",
    city:       "Ruston",
    state:      "Louisiana",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/louisiana-tech.svg"
  },
  {
    name:       "University of Louisville",
    name_short: "Louisville",
    abbrev:     "LOU",
    nickname:   "Cardinals",
    city:       "Louisville",
    state:      "Kentucky",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/louisville.svg"
  },
  {
    name:       "Louisiana State University",
    name_short: "LSU",
    abbrev:     "LSU",
    nickname:   "Tigers",
    city:       "Baton Rouge",
    state:      "Louisiana",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/lsu.svg"
  },
  {
    name:       "Marshall University",
    name_short: "Marshall",
    abbrev:     "MRSH",
    nickname:   "Thundering Herd",
    city:       "Huntington",
    state:      "West Virginia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/marshall.svg"
  },
  {
    name:       "University of Maryland",
    name_short: "Maryland",
    abbrev:     "MD",
    nickname:   "Terrapins",
    city:       "College Park",
    state:      "Maryland",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/maryland.svg"
  },
  {
    name:       "University of Memphis",
    name_short: "Memphis",
    abbrev:     "MEM",
    nickname:   "Tigers",
    city:       "Memphis",
    state:      "Tennessee",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/memphis.svg"
  },
  {
    name:       "University of Miami",
    name_short: "Miami (FL)",
    abbrev:     "MIA",
    nickname:   "Hurricanes",
    city:       "Coral Gables",
    state:      "Florida",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/miami-fl.svg"
  },
  {
    name:       "Miami University",
    name_short: "Miami (OH)",
    abbrev:     "M-OH",
    nickname:   "RedHawks",
    city:       "Oxford",
    state:      "Ohio",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/miami-oh.svg"
  },
  {
    name:       "University of Michigan",
    name_short: "Michigan",
    abbrev:     "MICH",
    nickname:   "Wolverines",
    city:       "Ann Arbor",
    state:      "Michigan",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/michigan.svg"
  },
  {
    name:       "Michigan State University",
    name_short: "Michigan St.",
    abbrev:     "MSU",
    nickname:   "Spartans",
    city:       "East Lansing",
    state:      "Michigan",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/michigan-st.svg"
  },
  {
    name:       "Middle Tennessee State University",
    name_short: "Middle Tenn.",
    abbrev:     "MTSU",
    nickname:   "Blue Raiders",
    city:       "Murfreesboro",
    state:      "Tennessee",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/middle-tenn.svg"
  },
  {
    name:       "University of Minnesota",
    name_short: "Minnesota",
    abbrev:     "MINN",
    nickname:   "Golden Gophers",
    city:       "Minneapolis",
    state:      "Minnesota",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/minnesota.svg"
  },
  {
    name:       "Mississippi State University",
    name_short: "Miss. State",
    abbrev:     "MSST",
    nickname:   "Bulldogs",
    city:       "Starkville",
    state:      "Mississippi",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/mississippi-st.svg"
  },
  {
    name:       "University of Missouri",
    name_short: "Missouri",
    abbrev:     "MIZ",
    nickname:   "Tigers",
    city:       "Columbia",
    state:      "Missouri",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/missouri.svg"
  },
  {
    name:       "United States Naval Academy",
    name_short: "Navy",
    abbrev:     "NAVY",
    nickname:   "Midshipmen",
    city:       "Annapolis",
    state:      "Maryland",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/navy.svg"
  },
  {
    name:       "North Carolina State University",
    name_short: "NC State",
    abbrev:     "NCST",
    nickname:   "Wolfpack",
    city:       "Raleigh",
    state:      "North Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/north-carolina-st.svg"
  },
  {
    name:       "University of Nebraska",
    name_short: "Nebraska",
    abbrev:     "NEB",
    nickname:   "Cornhuskers",
    city:       "Lincoln",
    state:      "Nebraska",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/nebraska.svg"
  },
  {
    name:       "University of Nevada",
    name_short: "Nevada",
    abbrev:     "NEV",
    nickname:   "Wolf Pack",
    city:       "Reno",
    state:      "Nevada",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/nevada.svg"
  },
  {
    name:       "University of New Mexico",
    name_short: "New Mexico",
    abbrev:     "UNM",
    nickname:   "Lobos",
    city:       "Albuquerque",
    state:      "New Mexico",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/new-mexico.svg"
  },
  {
    name:       "New Mexico State University",
    name_short: "New Mexico St.",
    abbrev:     "NMSU",
    nickname:   "Aggies",
    city:       "Las Cruces",
    state:      "New Mexico",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/new-mexico-st.svg"
  },
  {
    name:       "University of North Carolina",
    name_short: "North Carolina",
    abbrev:     "UNC",
    nickname:   "Tar Heels",
    city:       "Chapel Hill",
    state:      "North Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/north-carolina.svg"
  },
  {
    name:       "University of North Texas",
    name_short: "North Texas",
    abbrev:     "UNT",
    nickname:   "Mean Green",
    city:       "Denton",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/north-texas.svg"
  },
  {
    name:       "Northern Illinois University",
    name_short: "Northern Ill.",
    abbrev:     "NIU",
    nickname:   "Huskies",
    city:       "De Kalb",
    state:      "Illinois",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/northern-ill.svg"
  },
  {
    name:       "Northwestern University",
    name_short: "Northwestern",
    abbrev:     "NU",
    nickname:   "Wildcats",
    city:       "Evanston",
    state:      "Illinois",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/northwestern.svg"
  },
  {
    name:       "University of Notre Dame",
    name_short: "Notre Dame",
    abbrev:     "ND",
    nickname:   "Fighting Irish",
    city:       "South Bend",
    state:      "Indiana",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/notre-dame.svg"
  },
  {
    name:       "Ohio University",
    name_short: "Ohio",
    abbrev:     "OHIO",
    nickname:   "Bobcats",
    city:       "Athens",
    state:      "Ohio",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/ohio.svg"
  },
  {
    name:       "Ohio State University",
    name_short: "Ohio St.",
    abbrev:     "OSU",
    nickname:   "Buckeyes",
    city:       "Columbus",
    state:      "Ohio",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/ohio-st.svg"
  },
  {
    name:       "University of Oklahoma",
    name_short: "Oklahoma",
    abbrev:     "OU",
    nickname:   "Sooners",
    city:       "Norman",
    state:      "Oklahoma",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/oklahoma.svg"
  },
  {
    name:       "Oklahoma State University",
    name_short: "Oklahoma St.",
    abbrev:     "OKST",
    nickname:   "Cowboys",
    city:       "Stillwater",
    state:      "Oklahoma",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/oklahoma-st.svg"
  },
  {
    name:       "Old Dominion University",
    name_short: "Old Dominion",
    abbrev:     "ODU",
    nickname:   "Monarchs",
    city:       "Norfolk",
    state:      "Virginia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/old-dominion.svg"
  },
  {
    name:       "University of Mississippi",
    name_short: "Ole Miss",
    abbrev:     "MISS",
    nickname:   "Rebels",
    city:       "University",
    state:      "Mississippi",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/ole-miss.svg"
  },
  {
    name:       "University of Oregon",
    name_short: "Oregon",
    abbrev:     "ORE",
    nickname:   "Ducks",
    city:       "Eugene",
    state:      "Oregon",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/oregon.svg"
  },
  {
    name:       "Oregon State University",
    name_short: "Oregon St.",
    abbrev:     "ORST",
    nickname:   "Beavers",
    city:       "Corvallis",
    state:      "Oregon",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/oregon-st.svg"
  },
  {
    name:       "Penn State University",
    name_short: "Penn St.",
    abbrev:     "PSU",
    nickname:   "Nittany Lions",
    city:       "University Park",
    state:      "Pennsylvania",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/penn-st.svg"
  },
  {
    name:       "University of Pittsburgh",
    name_short: "Pittsburgh",
    abbrev:     "PITT",
    nickname:   "Panthers",
    city:       "Pittsburgh",
    state:      "Pennsylvania",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/pittsburgh.svg"
  },
  {
    name:       "Purdue University",
    name_short: "Purdue",
    abbrev:     "PUR",
    nickname:   "Boilermakers",
    city:       "West Lafayette",
    state:      "Indiana",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/purdue.svg"
  },
  {
    name:       "William Marsh Rice University",
    name_short: "Rice",
    abbrev:     "RICE",
    nickname:   "Owls",
    city:       "Houston",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/rice.svg"
  },
  {
    name:       "Rutgers University",
    name_short: "Rutgers",
    abbrev:     "RUTG",
    nickname:   "Scarlet Knights",
    city:       "New Brunswick",
    state:      "New Jersey",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/rutgers.svg"
  },
  {
    name:       "Sam Houston State University",
    name_short: "Sam Houston",
    abbrev:     "",
    nickname:   "Bearkats",
    city:       "Huntsville",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "San Diego State University",
    name_short: "San Diego St.",
    abbrev:     "SDST",
    nickname:   "Aztecs",
    city:       "San Diego",
    state:      "California",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/san-diego-st.svg"
  },
  {
    name:       "San Jose State University",
    name_short: "San Jose St.",
    abbrev:     "SJST",
    nickname:   "Spartans",
    city:       "San Jose",
    state:      "California",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/san-jose-st.svg"
  },
  {
    name:       "Southern Methodist University",
    name_short: "SMU",
    abbrev:     "SMU",
    nickname:   "Mustangs",
    city:       "University Park",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/smu.svg"
  },
  {
    name:       "University of South Alabama",
    name_short: "South Ala.",
    abbrev:     "USA",
    nickname:   "Jaguars",
    city:       "Mobile",
    state:      "Alabama",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/south-ala.svg"
  },
  {
    name:       "University of South Carolina",
    name_short: "South Carolina",
    abbrev:     "SC",
    nickname:   "Gamecocks",
    city:       "Columbia",
    state:      "South Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/south-carolina.svg"
  },
  {
    name:       "University of South Florida",
    name_short: "South Florida",
    abbrev:     "USF",
    nickname:   "Bulls",
    city:       "Tampa",
    state:      "Florida",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/south-fla.svg"
  },
  {
    name:       "University of Southern Mississippi",
    name_short: "Southern Miss.",
    abbrev:     "USM",
    nickname:   "Golden Eagles",
    city:       "Hattiesburg",
    state:      "Mississippi",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/southern-miss.svg"
  },
  {
    name:       "Stanford University",
    name_short: "Stanford",
    abbrev:     "STAN",
    nickname:   "Cardinal",
    city:       "Stanford",
    state:      "California",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/stanford.svg"
  },
  {
    name:       "Syracuse University",
    name_short: "Syracuse",
    abbrev:     "SYR",
    nickname:   "Orange",
    city:       "Syracuse",
    state:      "New York",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/syracuse.svg"
  },
  {
    name:       "Texas Christian University",
    name_short: "TCU",
    abbrev:     "TCU",
    nickname:   "Horned Frogs",
    city:       "Fort Worth",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/tcu.svg"
  },
  {
    name:       "Temple University",
    name_short: "Temple",
    abbrev:     "TEM",
    nickname:   "Owls",
    city:       "Philidelphia",
    state:      "Pennsylvania",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/temple.svg"
  },
  {
    name:       "University of Tennessee",
    name_short: "Tennessee",
    abbrev:     "",
    nickname:   "Volunteers",
    city:       "Knoxville",
    state:      "Tennessee",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/tennessee.svg"
  },
  {
    name:       "University of Texas at Austin",
    name_short: "Texas",
    abbrev:     "",
    nickname:   "Longhorns",
    city:       "Austin",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   "https://i.turner.ncaa.com/sites/default/files/images/logos/schools/bgd/texas.svg"
  },
  {
    name:       "Texas A&M University",
    name_short: "Texas A&M",
    abbrev:     "",
    nickname:   "Aggies",
    city:       "College Station",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Texas State University",
    name_short: "Texas State",
    abbrev:     "",
    nickname:   "Bobcats",
    city:       "San Marcos",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Texas Tech University",
    name_short: "Texas Tech",
    abbrev:     "",
    nickname:   "Red Raiders",
    city:       "Lubbock",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Toledo",
    name_short: "Toledo",
    abbrev:     "",
    nickname:   "Rockets",
    city:       "Toledo",
    state:      "Ohio",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Troy University",
    name_short: "Troy",
    abbrev:     "",
    nickname:   "Trojans",
    city:       "Troy",
    state:      "Alabama",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Tulane University",
    name_short: "Tulane",
    abbrev:     "",
    nickname:   "Green Wave",
    city:       "New Orleans",
    state:      "Louisiana",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Tulsa",
    name_short: "Tulsa",
    abbrev:     "",
    nickname:   "Golden Hurricane",
    city:       "Tulsa",
    state:      "Oklahoma",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Alabama at Birmingham",
    name_short: "UAB",
    abbrev:     "UAB",
    nickname:   "Blazers",
    city:       "Birmingham",
    state:      "Alabama",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Central Florida",
    name_short: "UCF",
    abbrev:     "UCF",
    nickname:   "Knights",
    city:       "Orlando",
    state:      "Florida",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of California, Los Angeles",
    name_short: "UCLA",
    abbrev:     "UCLA",
    nickname:   "Bruins",
    city:       "Los Angeles",
    state:      "California",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Connecticut",
    name_short: "UConn",
    abbrev:     "UCONN",
    nickname:   "Huskies",
    city:       "Storrs",
    state:      "Connecticut",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Massachusetts Amherst",
    name_short: "UMass",
    abbrev:     "",
    nickname:   "Minutemen",
    city:       "Amherst",
    state:      "Massachusetts",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Nevada, Las Vegas",
    name_short: "UNLV",
    abbrev:     "UNLV",
    nickname:   "Rebels",
    city:       "Las Vegas",
    state:      "Nevada",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Southern California",
    name_short: "USC",
    abbrev:     "USC",
    nickname:   "Trojans",
    city:       "Los Angeles",
    state:      "California",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Texas at El Paso",
    name_short: "UTEP",
    abbrev:     "UTEP",
    nickname:   "Miners",
    city:       "El Paso",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Texas at San Antonio",
    name_short: "UTSA",
    abbrev:     "UTSA",
    nickname:   "Roadrunners",
    city:       "San Antonio",
    state:      "Texas",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Utah",
    name_short: "Utah",
    abbrev:     "",
    nickname:   "Utes",
    city:       "Salt Lake City",
    state:      "Utah",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Utah State University",
    name_short: "Utah St.",
    abbrev:     "",
    nickname:   "Aggies",
    city:       "Logan",
    state:      "Utah",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Vanderbilt University",
    name_short: "Vanderbilt",
    abbrev:     "",
    nickname:   "Commodores",
    city:       "Nashville",
    state:      "Tennessee",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Virginia",
    name_short: "Virginia",
    abbrev:     "",
    nickname:   "Cavaliers",
    city:       "Charlottesville",
    state:      "Virginia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Virginia Tech",
    name_short: "Virginia Tech",
    abbrev:     "",
    nickname:   "Hokies",
    city:       "Blacksburg",
    state:      "Virginia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Wake Forest University",
    name_short: "Wake Forest",
    abbrev:     "WAKE",
    nickname:   "Demon Deacons",
    city:       "Winston-Salem",
    state:      "North Carolina",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Washington",
    name_short: "Washington",
    abbrev:     "",
    nickname:   "Huskies",
    city:       "Seattle",
    state:      "Washington",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Washington State University",
    name_short: "Washington St.",
    abbrev:     "",
    nickname:   "Cougars",
    city:       "Pullman",
    state:      "Washington",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "West Virginia University",
    name_short: "W. Virginia",
    abbrev:     "",
    nickname:   "Mountaineers",
    city:       "Morgantown",
    state:      "West Virginia",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Western Kentucky University",
    name_short: "W. Kentucky",
    abbrev:     "",
    nickname:   "Hilltoppers",
    city:       "Bowling Green",
    state:      "Kentucky",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "Western Michigan University",
    name_short: "W. Michigan",
    abbrev:     "",
    nickname:   "Broncos",
    city:       "Kalamazoo",
    state:      "Michigan",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Wisconsin, Madison",
    name_short: "Wisconsin",
    abbrev:     "",
    nickname:   "Badgers",
    city:       "Madison",
    state:      "Wisconsin",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  },
  {
    name:       "University of Wyoming",
    name_short: "Wyoming",
    abbrev:     "",
    nickname:   "Cowboys",
    city:       "Laramie",
    state:      "Wyoming",
    color_bg:   "",
    color_fg:   "",
    logo_url:   ""
  }
])
